name: CI Pipeline
on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  security:
    uses: ISSEL-labgroup/security-template/.github/workflows/security-checks.yml@actions
    secrets: inherit
